- hosts: all

  vars:
    sudoers:
      - user

  tasks:
    - name: Check sudo group is present
      group:
        name: sudo
        state: present

    - name: Make sudo group members to use passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^%sudo"
        line: "%sudo ALL=(ALL:ALL) NOPASSWD: ALL"
        validate: visudo -cf %s
      become: yes

    - name: Add users to sudo group
      user:
        name: "{{ item }}"
        groups: sudo
        append: yes
      with_items: "{{ sudoers }}"
      become: yes
