- hosts: linux

  tasks:
    - name: Install 'tzdata' package
      apt:
        name: tzdata
      become: yes

    - name: Setup /etc/localtime
      file:
        src: /usr/share/zoneinfo/Europe/Moscow
        dest: /etc/localtime
        state: link
        force: yes
      become: yes

    - name: Setup /etc/timezone
      blockinfile:
        path: /etc/localtime
        block: "Europe/Moscow"
      become: yes
